# Generated by Django 5.2.3 on 2025-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nim", models.CharField(max_length=15, unique=True)),
                ("nama", models.CharField(max_length=100)),
                ("jurusan", models.CharField(max_length=100)),
                ("angkatan", models.IntegerField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
