# Generated by Django 5.2.3 on 2025-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_matakuliah_submission_grade_tugas_submission_tugas"),
    ]

    operations = [
        migrations.AddField(
            model_name="matakuliah",
            name="kode",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
