# Generated by Django 5.2.3 on 2025-10-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_matakuliah_kode"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahasiswa",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="no_wa",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="tanggal_lahir",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="tempat_lahir",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
