# Generated by Django 5.2.3 on 2025-10-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_mahasiswa_alamat_mahasiswa_no_wa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="file",
        ),
        migrations.AddField(
            model_name="submission",
            name="drive_file_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="drive_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
