# Generated by Django 5.2.3 on 2025-10-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_submission_file_submission_drive_file_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="drive_link",
            new_name="link_tugas",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="drive_file_id",
        ),
    ]
